### ISSUE TITLE
Remove raw secrets values from exceptions

### ISSUE THREAD

**Issue by bplociennik** [merixstudio/simple-storage#6]
Package in case if some of the envs are configured wrongly prints out an error.
`ERROR tests/test_aws_s3_storage.py::TestAWSS3Storage::test_file_modification_time - storages.exceptions.ImproperlyConfiguredError: The 'aws_access_key_id' setting has improper value of: 'None'`

I think would be better to not print values in that cases. It gives an easier way to extract protected credentials from the system.

```
if not aws_access_key_id:
    raise ImproperlyConfiguredError(
        name="aws_access_key_id", value=aws_access_key_id
    )
```

**Comment by allow-cookies** [comment]
Fixed in release `0.0.6` ✔️
